quantityOfPositions = 5
maxPositionDuration = 90
fileName = 'output'
pricesFileName = '20180101-20191231.json'
positionsColumns = [
    'OPEN_DAY',
    'CLOSE_DAY',
    'POSITION_DURATION',
    'PROFIT',
    'PROFIT_PERCENT',
    'OPEN_PRICE',
    'CLOSE_PRICE',
    'OPEN_RSI',
    'CLOSE_RSI',
    'OPEN_SMA_20',
    'CLOSE_SMA_20',
    'OPEN_SMA_50',
    'CLOSE_SMA_50',
    'OPEN_SMA_100',
    'CLOSE_SMA_100',
    'OPEN_SMA_200',
    'CLOSE_SMA_200',
    'OPEN_EMA_20',
    'CLOSE_EMA_20',
    'OPEN_EMA_50',
    'CLOSE_EMA_50',
    'OPEN_EMA_100',
    'CLOSE_EMA_100',
    'OPEN_EMA_200',
    'CLOSE_EMA_200',
    'OPEN_BB_HIGH_1',
    'CLOSE_BB_HIGH_1',
    'OPEN_BB_HIGH_2',
    'CLOSE_BB_HIGH_2',
    'OPEN_BB_LOW_1',
    'CLOSE_BB_LOW_1',
    'OPEN_BB_LOW_2',
    'CLOSE_BB_LOW_2',
    'OPEN_BB_WIDTH_1',
    'CLOSE_BB_WIDTH_1',
    'OPEN_BB_WIDTH_2',
    'CLOSE_BB_WIDTH_2',
    'OPEN_MACD_DEFAULT',
    'CLOSE_MACD_DEFAULT',
    'OPEN_MACD_200_50_20',
    'CLOSE_MACD_200_50_20',
    'CLASS',
]
